import { SubMaterialItem, ItemStatus } from './types';

export const MOCK_DATA: SubMaterialItem[] = [
  {
    id: '1',
    productCode: '9ABC1234567',
    productName: '글로우틴트#01스트로베리',
    salesYearMonth: '26.01',
    salesQuantity: 500,
    totalSalesPrice: 650,
    subMaterialSalesPrice: 120,
    subMaterialPurchasePrice: 150,
    priceDifference: 30,
    totalDifference: 15000,
    salesManager: '홍길동',
    closingManager: '감딸기',
    purchaseManager: '원가온',
    customerCode: '101234',
    customerName: '꿈빛코스메틱',
    customerAbbr: 'ABC',
    status: ItemStatus.INCOMPLETE,
    updatedAt: '2026-01-31',
  },
  {
    id: '2',
    productCode: '9DEF7890123',
    productName: '벨벳립스틱#05로즈',
    salesYearMonth: '26.01',
    salesQuantity: 1200,
    totalSalesPrice: 850,
    subMaterialSalesPrice: 180,
    subMaterialPurchasePrice: 210,
    priceDifference: 30,
    totalDifference: 36000,
    salesManager: '이몽룡',
    closingManager: '성춘향',
    purchaseManager: '원가온',
    customerCode: '105678',
    customerName: '뷰티풀데이즈',
    customerAbbr: 'BTD',
    status: ItemStatus.INCOMPLETE,
    updatedAt: '2026-01-31',
  },
  {
    id: '3',
    productCode: '9GHI4567890',
    productName: '수분크림 50ml',
    salesYearMonth: '26.01',
    salesQuantity: 300,
    totalSalesPrice: 1500,
    subMaterialSalesPrice: 450,
    subMaterialPurchasePrice: 480,
    priceDifference: 30,
    totalDifference: 9000,
    salesManager: '홍길동',
    closingManager: '감딸기',
    purchaseManager: '원가온',
    customerCode: '101234',
    customerName: '꿈빛코스메틱',
    customerAbbr: 'ABC',
    status: ItemStatus.COMPLETED,
    updatedAt: '2026-02-15',
  },
  {
    id: '4',
    productCode: '9JKL1234567',
    productName: '선스크린 SPF50+',
    salesYearMonth: '26.01',
    salesQuantity: 800,
    totalSalesPrice: 1200,
    subMaterialSalesPrice: 300,
    subMaterialPurchasePrice: 350,
    priceDifference: 50,
    totalDifference: 40000,
    salesManager: '김철수',
    closingManager: '박영희',
    purchaseManager: '원가온',
    customerCode: '109876',
    customerName: '글로벌코스메틱',
    customerAbbr: 'GLB',
    status: ItemStatus.INCOMPLETE,
    updatedAt: '2026-01-31',
  },
  {
    id: '5',
    productCode: '9MNO5678901',
    productName: '아이라이너 블랙',
    salesYearMonth: '26.01',
    salesQuantity: 2000,
    totalSalesPrice: 450,
    subMaterialSalesPrice: 80,
    subMaterialPurchasePrice: 95,
    priceDifference: 15,
    totalDifference: 30000,
    salesManager: '이몽룡',
    closingManager: '성춘향',
    purchaseManager: '원가온',
    customerCode: '105678',
    customerName: '뷰티풀데이즈',
    customerAbbr: 'BTD',
    status: ItemStatus.INCOMPLETE,
    updatedAt: '2026-01-31',
  }
];
